name: Test

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        os: [ubuntu-latest] # [ubuntu-latest, windows-latest, macos-latest]
        pydantic-version: ['>=1.10,<2', '>=2.6']
        exclude:
          - python-version: '3.14'
            pydantic-version: '>=1.10,<2'
      fail-fast: false

    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      code-quality: write
    env:
      OS: ${{ matrix.os }}
      PYTHON_VERSION: ${{ matrix.python-version }}
      PYDANTIC_VERSION: ${{ matrix.pydantic-version }}

    steps:
      - name: Set up workspace
        uses: lgc-NB2Dev/workspace/.github/actions/setup-workspace@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Specific Version Pydantic (Bash)
        shell: bash
        run: uv add "pydantic$PYDANTIC_VERSION"

      - name: Run pytest with coverage
        working-directory: plugins/${{ github.event.repository.name }}
        shell: bash
        env:
          PLUGIN_MODULE: ${{ github.event.repository.name }}
        run: >-
          uv run pytest
          --cov="${PLUGIN_MODULE//-/_}"
          --cov-branch
          --cov-report=xml:coverage.xml
          --cov-report=markdown-append:"$GITHUB_STEP_SUMMARY"

      - name: Upload coverage report
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-code-coverage@v1
        with:
          file: plugins/${{ github.event.repository.name }}/coverage.xml
          language: Python
          label: code-coverage/pytest
